# Generated by Django 3.1.7 on 2021-03-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer_review',
            field=models.CharField(default=100, max_length=300),
        ),
    ]
