# Generated by Django 3.1.7 on 2021-03-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_customer_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='lorem ipsum', max_length=50),
        ),
    ]
