# Generated by Django 3.1.7 on 2021-03-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
        migrations.AlterField(
            model_name='product',
            name='customer_review',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
